/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o '/home/carol/Desktop/Semester 10/Core/Compilers Lab/M2/NumberTwo/nimcache/test.o' '/home/carol/Desktop/Semester 10/Core/Compilers Lab/M2/NumberTwo/nimcache/test.c' */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, caesar_9b70LPbYXV9cNQY9bM31v4s8g)(NimStringDesc* s, NI k, NIM_BOOL decode);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_3, "", 0);
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_9, "len(a) == L string modified while iterating over it", 51);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, caesar_9b70LPbYXV9cNQY9bM31v4s8g)(NimStringDesc* s, NI k, NIM_BOOL decode) {
	NimStringDesc* result;
	NI k_2;
	nimfr_("caesar", "test.nim");
	result = (NimStringDesc*)0;
	nimln_(4, "test.nim");
	{
		NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_2;
		if (!decode) goto LA3_;
		TM_ipcYmBC9bj9a1BW35ABoB1Kw_2 = subInt(((NI) 26), k);
		k_2 = (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_2);
	}
	goto LA1_;
	LA3_: ;
	{
		k_2 = k;
	}
	LA1_: ;
	nimln_(5, "test.nim");
	result = copyString(((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_3));
	{
		NIM_CHAR i;
		NimStringDesc* colontmp_;
		NI i_2;
		NI L;
		i = (NIM_CHAR)0;
		colontmp_ = (NimStringDesc*)0;
		nimln_(6, "test.nim");
		colontmp_ = nsuToUpperStr(s);
		nimln_(3657, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3658, "system.nim");
		L = (colontmp_ ? colontmp_->Sup.len : 0);
		{
			nimln_(3659, "system.nim");
			while (1) {
				NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_8;
				if (!(i_2 < L)) goto LA8;
				nimln_(3660, "system.nim");
				if ((NU)(i_2) > (NU)(colontmp_->Sup.len)) raiseIndexError();
				i = colontmp_->data[i_2];
				nimln_(7, "test.nim");
				{
					NIM_BOOL T11_;
					NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_4;
					NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_5;
					NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_6;
					NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_7;
					T11_ = (NIM_BOOL)0;
					T11_ = (((NI) 65) <= ((NI) (((NU8)(i)))));
					if (!(T11_)) goto LA12_;
					T11_ = (((NI) (((NU8)(i)))) <= ((NI) 90));
					LA12_: ;
					if (!T11_) goto LA13_;
					nimln_(8, "test.nim");
					TM_ipcYmBC9bj9a1BW35ABoB1Kw_4 = subInt(((NI) (((NU8)(i)))), ((NI) 65));
					TM_ipcYmBC9bj9a1BW35ABoB1Kw_5 = addInt(((NI) ((NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_4))), k_2);
					TM_ipcYmBC9bj9a1BW35ABoB1Kw_6 = modInt((NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_5), ((NI) 26));
					TM_ipcYmBC9bj9a1BW35ABoB1Kw_7 = addInt(((NI) ((NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_6))), ((NI) 65));
					result = addChar(result, ((NIM_CHAR) (((NI) ((NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_7))))));
				}
				LA13_: ;
				nimln_(3661, "system.nim");
				TM_ipcYmBC9bj9a1BW35ABoB1Kw_8 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_8);
				nimln_(3662, "system.nim");
				{
					if (!!(((colontmp_ ? colontmp_->Sup.len : 0) == L))) goto LA17_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_9));
				}
				LA17_: ;
			} LA8: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	testDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("test", "test.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void) {
}

